package pe.edu.unsch.entities;
// Generated 12-jul-2019 8:19:31 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargaacademica generated by hbm2java
 */
@Entity
@Table(name = "cargaacademica", catalog = "cargabd1")
public class Cargaacademica implements java.io.Serializable {

	private int idcargaacademica;
	private String horascargaacademica;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Cargaacademica() {
	}

	public Cargaacademica(int idcargaacademica, String horascargaacademica) {
		this.idcargaacademica = idcargaacademica;
		this.horascargaacademica = horascargaacademica;
	}

	public Cargaacademica(int idcargaacademica, String horascargaacademica, Set<Docente> docentes) {
		this.idcargaacademica = idcargaacademica;
		this.horascargaacademica = horascargaacademica;
		this.docentes = docentes;
	}

	@Id

	@Column(name = "idcargaacademica", unique = true, nullable = false)
	public int getIdcargaacademica() {
		return this.idcargaacademica;
	}

	public void setIdcargaacademica(int idcargaacademica) {
		this.idcargaacademica = idcargaacademica;
	}

	@Column(name = "horascargaacademica", nullable = false, length = 45)
	public String getHorascargaacademica() {
		return this.horascargaacademica;
	}

	public void setHorascargaacademica(String horascargaacademica) {
		this.horascargaacademica = horascargaacademica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargaacademica")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
