package pe.edu.unsch.entities;
// Generated 11-jul-2019 16:44:22 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd")
public class Docente implements java.io.Serializable {

	private int iddocente;
	private String nombredocente;
	private Set<Semestreacademico> semestreacademicos = new HashSet<Semestreacademico>(0);

	public Docente() {
	}

	public Docente(int iddocente, String nombredocente) {
		this.iddocente = iddocente;
		this.nombredocente = nombredocente;
	}

	public Docente(int iddocente, String nombredocente, Set<Semestreacademico> semestreacademicos) {
		this.iddocente = iddocente;
		this.nombredocente = nombredocente;
		this.semestreacademicos = semestreacademicos;
	}

	@Id

	@Column(name = "iddocente", unique = true, nullable = false)
	public int getIddocente() {
		return this.iddocente;
	}

	public void setIddocente(int iddocente) {
		this.iddocente = iddocente;
	}

	@Column(name = "nombredocente", nullable = false, length = 50)
	public String getNombredocente() {
		return this.nombredocente;
	}

	public void setNombredocente(String nombredocente) {
		this.nombredocente = nombredocente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Semestreacademico> getSemestreacademicos() {
		return this.semestreacademicos;
	}

	public void setSemestreacademicos(Set<Semestreacademico> semestreacademicos) {
		this.semestreacademicos = semestreacademicos;
	}

}
