package pe.edu.unsch.entities;
// Generated 12-jul-2019 8:19:31 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargabd1")
public class Docente implements java.io.Serializable {

	private int iddocente;
	private Cargaacademica cargaacademica;
	private Semestreacademico semestreacademico;
	private String nombredocente;

	public Docente() {
	}

	public Docente(int iddocente, Cargaacademica cargaacademica, Semestreacademico semestreacademico,
			String nombredocente) {
		this.iddocente = iddocente;
		this.cargaacademica = cargaacademica;
		this.semestreacademico = semestreacademico;
		this.nombredocente = nombredocente;
	}

	@Id

	@Column(name = "iddocente", unique = true, nullable = false)
	public int getIddocente() {
		return this.iddocente;
	}

	public void setIddocente(int iddocente) {
		this.iddocente = iddocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cargaacademica_idcargaacademica", nullable = false)
	public Cargaacademica getCargaacademica() {
		return this.cargaacademica;
	}

	public void setCargaacademica(Cargaacademica cargaacademica) {
		this.cargaacademica = cargaacademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "semestreacademico_idsemestreacademico", nullable = false)
	public Semestreacademico getSemestreacademico() {
		return this.semestreacademico;
	}

	public void setSemestreacademico(Semestreacademico semestreacademico) {
		this.semestreacademico = semestreacademico;
	}

	@Column(name = "nombredocente", nullable = false, length = 50)
	public String getNombredocente() {
		return this.nombredocente;
	}

	public void setNombredocente(String nombredocente) {
		this.nombredocente = nombredocente;
	}

}
