package pe.edu.unsch.entities;
// Generated 11-jul-2019 16:44:22 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Semestreacademico generated by hbm2java
 */
@Entity
@Table(name = "semestreacademico", catalog = "cargabd")
public class Semestreacademico implements java.io.Serializable {

	private int idsemestreacademico;
	private Docente docente;
	private String numerosemestreacademico;
	private int cargaacademica;

	public Semestreacademico() {
	}

	public Semestreacademico(int idsemestreacademico, Docente docente, String numerosemestreacademico,
			int cargaacademica) {
		this.idsemestreacademico = idsemestreacademico;
		this.docente = docente;
		this.numerosemestreacademico = numerosemestreacademico;
		this.cargaacademica = cargaacademica;
	}

	@Id

	@Column(name = "idsemestreacademico", unique = true, nullable = false)
	public int getIdsemestreacademico() {
		return this.idsemestreacademico;
	}

	public void setIdsemestreacademico(int idsemestreacademico) {
		this.idsemestreacademico = idsemestreacademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docente_iddocente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "numerosemestreacademico", nullable = false, length = 50)
	public String getNumerosemestreacademico() {
		return this.numerosemestreacademico;
	}

	public void setNumerosemestreacademico(String numerosemestreacademico) {
		this.numerosemestreacademico = numerosemestreacademico;
	}

	@Column(name = "cargaacademica", nullable = false)
	public int getCargaacademica() {
		return this.cargaacademica;
	}

	public void setCargaacademica(int cargaacademica) {
		this.cargaacademica = cargaacademica;
	}

}
